set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=white,bg=black' 
set -g @prefix_highlight_show_sync_mode 'on'
set -g @prefix_highlight_sync_mode_attr 'fg=white,bg=black'
set -g @prefix_highlight_fg 'white'
set -g @prefix_highlight_bg 'black'
set -g @prefix_highlight_prefix_prompt 'Prefix'

set -g history-limit 10000

bind-key -n M-BSpace send-keys C-w

unbind C-b
set -g prefix M-Space
bind M-Space send-prefix

set -sg escape-time 0

bind -n M-c new-window
bind -n M-x kill-pane
bind -n M-& kill-window
bind -n M-v copy-mode

setw -g monitor-activity on

bind r source-file ~/.tmux.conf \; display-message "Configuration reloaded."

set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -s extended-keys on
set -g xterm-keys on

bind -n M-p previous-window
bind -n M-n next-window

bind -n M-P swap-window -t -1 \; previous-window
bind -n M-N swap-window -t +1 \; next-window

bind-key & kill-window
bind-key x kill-pane

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# bind-key -n M-Up    resize-pane -U 5
# bind-key -n M-Down  resize-pane -D 5
# bind-key -n M-Left  resize-pane -L 5
# bind-key -n M-Right resize-pane -R 5

set-window-option -g automatic-rename on
set-option -g set-titles on

bind-key Space display-menu -T "Choose a Layout" -x C -y C \
    "Even Horizontal"  h "select-layout even-horizontal" \
    "Even Vertical"    v "select-layout even-vertical" \
    "Main Horizontal"  H "select-layout main-horizontal" \
    "Main Vertical"    V "select-layout main-vertical" \
    "Tiled"            t "select-layout tiled" \
    "" \
    "Close Menu"       q ""

set -g status-style                 "bg=black,fg=white"
set -g status-left-style            "bg=black,fg=white"
set -g status-right-style           "bg=black,fg=white"
set -g window-status-style          "bg=black,fg=colour245"
set -g window-status-current-style  "bg=black,fg=white,bold"
set -g window-status-activity-style "bg=black,fg=white"
set -g pane-border-style            "fg=colour240"
set -g pane-active-border-style     "fg=white"
set -g message-style                "bg=black,fg=white"
set -g mode-style                   "bg=white,fg=black"

run '/opt/homebrew/opt/tpm/share/tpm/tpm'

