local M = { "nvim-neotest/neotest" }

M.dependencies = {
  "nvim-neotest/nvim-nio",
  "nvim-lua/plenary.nvim",
  {
    "nvim-neotest/neotest-plenary",
    dependencies = { "nvim-neotest/neotest" },
  },
  {
    "nvim-neotest/neotest-jest",
    dependencies = { "nvim-neotest/neotest" },
  },
}

M.keys = {
  { "<leader>tr", function() require("neotest").run.run() end,                                    desc = "Neotest: Run nearest" },
  { "<leader>tf", function() require("neotest").run.run(vim.fn.expand("%")) end,                  desc = "Neotest: Run file" },
  { "<leader>ts", function() require("neotest").run.run({ suite = true }) end,                    desc = "Neotest: Run suite" },
  { "<leader>tl", function() require("neotest").run.run_last() end,                               desc = "Neotest: Run last" },
  { "<leader>to", function() require("neotest").output.open() end,                                desc = "Neotest: Toggle output" },
  { "<leader>tO", function() require("neotest").summary.toggle() end,                             desc = "Neotest: Toggle summary" },
  { "<leader>td", function() require("neotest").run.run({ strategy = "dap", suite = false }) end, desc = "Neotest: Debug nearest" },
}

M.config = function()
  require("neotest").setup({
    log_level = vim.log.levels.WARN,
    adapters = {
      require("neotest-plenary"),
      require("neotest-jest")({
        jestCommand = "jest",
        jestConfigFile = "jest.config.*",
      }),
    },
    discovery = { enabled = true, concurrent = 0, filter_dir = nil },
    running = { concurrent = true },
    consumers = {},
    icons = {
      running_animated = { "/", "|", "\\", "-", "/", "|", "\\", "-" },
      passed = "",
      running = "",
      failed = "",
      skipped = "",
      unknown = "",
      non_collapsible = "─",
      collapsed = "─",
      expanded = "╮",
      child_prefix = "├",
      final_child_prefix = "╰",
      child_indent = "│",
      final_child_indent = " ",
      watching = "",
      test = "",
      notify = "",
      dir = "",
      file = "",
      namespace = "",
    },
    highlights = {
      passed = "NeotestPassed",
      running = "NeotestRunning",
      failed = "NeotestFailed",
      skipped = "NeotestSkipped",
      test = "NeotestTest",
      namespace = "NeotestNamespace",
      focused = "NeotestFocused",
      file = "NeotestFile",
      dir = "NeotestDir",
      border = "NeotestBorder",
      indent = "NeotestIndent",
      expand_marker = "NeotestExpandMarker",
      adapter_name = "NeotestAdapterName",
      select_win = "NeotestWinSelect",
      marked = "NeotestMarked",
      target = "NeotestTarget",
      unknown = "NeotestUnknown",
      watching = "NeotestWatching",
    },
    floating = { border = nil, max_height = 0.6, max_width = 0.6, options = {} },
    default_strategy = "integrated",
    strategies = { integrated = { width = 120, height = 40 } },
    summary = {
      enabled = true,
      count = true,
      animated = true,
      follow = true,
      expand_errors = true,
      open = "botright vsplit | vertical resize 50",
      mappings = {
        expand = { "<CR>", "<2-LeftMouse>" },
        expand_all = "e",
        parent = "P",
        prev_sibling = "<",
        next_sibling = ">",
        output = "o",
        short = "O",
        attach = "a",
        jumpto = "i",
        stop = "u",
        run = "r",
        debug = "d",
        mark = "m",
        run_marked = "R",
        debug_marked = "D",
        clear_marked = "M",
        target = "t",
        clear_target = "T",
        next_failed = "J",
        prev_failed = "K",
        watch = "w",
        help = "?",
      },
    },
    run = { enabled = true },
    output = { enabled = true, open_on_run = "short" },
    output_panel = { enabled = true, open = "botright split | resize 15" },
    quickfix = { enabled = true, open = false },
    status = { enabled = true, virtual_text = false, signs = true },
    state = { enabled = true },
    watch = {
      enabled = true,
      symbol_queries = {},
      filter_path = nil,
    },
    diagnostic = { enabled = true, severity = vim.diagnostic.severity.ERROR },
    projects = {},
  })
end

return M
